name: golangci-lint
description: Run golangci-lint with reviewdog
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  working_directory:
    description: working directory
    required: false
    default: ""
  timeout:
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: 'Link to Action: https://github.com/suzuki-shunsuke/github-action-golangci-lint'
      run: echo "::debug::Link to Action https://github.com/suzuki-shunsuke/github-action-golangci-lint"
      shell: bash

    - run: |
        echo "::error ::github_token is required. https://github.com/suzuki-shunsuke/github-action-golangci-lint"
        exit 1
      shell: bash
      if: inputs.github_token == ''

    - name: check golangci-lint is installed
      run: golangci-lint version
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - name: check reviewdog is installed
      run: reviewdog -version
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: golangci-lint
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
      run: |
        reporter=github-check
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          reporter=github-pr-review
        fi
        opts="--out-format checkstyle"
        if golangci-lint run --help | grep "output.checkstyle.path"; then
          opts="--output.checkstyle.path stdout"
        fi
        if [ -n "$INPUT_TIMEOUT" ]; then
          opts="$opts --timeout $INPUT_TIMEOUT"
        fi
        golangci-lint run $opts |
          reviewdog -f=checkstyle \
            -name="golangci-lint" \
            -filter-mode=nofilter \
            -reporter="$reporter" \
            -level=warning \
            -fail-on-error=1
